---
jupyter: python3
---

# Project Overview {-}

```{python}
#| echo: false
#| output: false
from content.python.api_calls_v2 import (
    get_habitat_stat_value,
    get_structure_count_value,
)

connected_habitat_km = get_habitat_stat_value(
    "CHETI", "as", "connected_naturally_accessible_habitat_km"
)
disconnected_habitat_km = get_habitat_stat_value(
    "CHETI", "as", "disconnected_naturally_accessible_habitat_km"
)
total_habitat_km = get_habitat_stat_value("CHETI", "as", "total_habitat_km")
connectivity_status_pct = get_habitat_stat_value(
    "CHETI", "as", "connectivity_status", digits=1
)

potentially_disconnect_structures = get_structure_count_value(
    "CHETI", "as", "structures_that_potentially_disconnect_habitat"
)
further_field_assessment = get_structure_count_value(
    "CHETI", "as", "require_further_assessment"
)
```

## Executive Summary {-}

The purpose of the Northeastern PEI Watershed Connectivity Restoration Plan (WCRP) is to improve understanding of habitat connectivity for Atlantic Salmon (*Salmo salar*), American Eel (*Anguilla rostrata*), and Rainbow Smelt (*Osmerus mordax*) in the North Lake Creek, Priest Pond Creek, Cross River, Hay River, Bear River, Naufrage River, and Cow River, herein referred to as the NE PEI watersheds, and inform efforts to close knowledge gaps and plan and prioritize restoration. Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 

In the NE PEI watersheds, X km of Atlantic Salmon habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total salmon habitat is connected. 

In the NE PEI watersheds, X km of American Eel habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total eel habitat is connected. 

In the NE PEI watersheds, X km of Rainbow Smelt habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total smelt habitat is connected. 

In the NE PEI watersheds, X structures potentially disconnect Atlantic Salmon and American Eel habitat. Of these, X are identified as barriers in need of rehabilitation (priority barriers), X are identified as barriers that do not warrant rehabilitation (non-actionable), and X require further field assessment. 

In the NE PEI watersheds, X structures potentially disconnect Rainbow Smelt. Of these, X are identified as barriers in need of rehabilitation (priority barriers), X are identified as barriers that do not warrant rehabilitation (non-actionable), and X require further field assessment. 

!["Figure 1: Map of Atlantic Salmon habitat and structures that are confirmed or potential barriers to fish passage in the NE PEI watersheds as of July 2026. Structure data were obtained from PEIFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that Atlantic Salmon could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by Atlantic Salmon for spawning and rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick orange lines represent partially disconnected habitat (upstream of a partial barrier), and thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not. "](content/images/Figure1.png){fig-cap-location="top"}

!["Figure 2: Map of American Eel habitat and structures that are confirmed or potential barriers to fish passage in the NE PEI watersheds as of July 2026. Structure data were obtained from PEIFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that American Eel could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by American Eel for feeding and growth. Available local knowledge and data were incorporated and overruled habitat model results. Thick orange lines represent partially disconnected habitat (upstream of a partial barrier), and thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not. "](content/images/Figure2.png){fig-cap-location="top"}

Figure 3: Map of Rainbow Smelt habitat and structures that are confirmed or potential barriers to fish passage in the NE PEI watersheds as of July 2026. Structure data were obtained from PEIFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that Rainbow Smelt could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by Rainbow Smelt for spawning and rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick orange lines represent partially disconnected habitat (upstream of a partial barrier), and thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not. 

!["Figure 4: Habitat Accumulation Curve (HAC) showing all structures (n=129) in the NE PEI watersheds that potentially block Atlantic Salmon habitat as of July 2026. Structures are ranked based on how much (km) weighted habitat for Atlantic Salmon is upstream. The y-axis represents the cumulative amount of potential habitat gain (km), down-weighted by 75% for first-order streams and 25% for second-order streams, and by passability (25%, 50%, or 75%) of partial barriers. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.  "](content/images/Figure4.png){fig-cap-location="top"}

!["Figure 5: Habitat Accumulation Curve (HAC) showing top-ranked structures (n=30) in the NE PEI watersheds that potentially block Atlantic Salmon habitat as of July 2026. Structures are ranked based on how much (km) weighted habitat for Atlantic Salmon is upstream. The y-axis represents the cumulative amount of potential habitat gain (km), down-weighted by 75% for first-order streams and 25% for second-order streams, and by passability (25%, 50%, or 75%) of partial barriers. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan. "](content/images/Figure5.png){fig-cap-location="top"}

!["Figure 6: Habitat Accumulation Curve (HAC) showing all structures (n=77) in the NE PEI watersheds that potentially block American Eel habitat as of July 2026. Structures are ranked based on how much (km) weighted habitat for American Eel is upstream. The y-axis represents the cumulative amount of potential habitat gain (km), down-weighted by 75% for first-order streams and 25% for second-order streams, and by passability (25%, 50%, or 75%) of partial barriers. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan. "](content/images/Figure6.png){fig-cap-location="top"}

!["Figure 7: Habitat Accumulation Curve (HAC) showing the top-ranked structures (n=30) in the NE PEI watersheds that potentially block American Eel habitat as of July 2026. Structures are ranked based on how much (km) weighted habitat for American Eel is upstream. The y-axis represents the cumulative amount of potential habitat gain (km), down-weighted by 75% for first-order streams and 25% for second-order streams, and by passability (25%, 50%, or 75%) of partial barriers. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan. "](content/images/Figure7.png){fig-cap-location="top"}

Figure 8: Habitat Accumulation Curve (HAC) showing top-ranked structures (XX) in the NE PEI watersheds that potentially block Rainbow Smelt habitat as of July 2026. Structures are ranked based on how much (km) weighted habitat for Rainbow Smelt is upstream. The y-axis represents the cumulative amount of potential habitat gain (km), down-weighted by 75% for first-order streams and 25% for second-order streams, and by passability (25%, 50%, or 75%) of partial barriers. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.  

This WCRP was initiated in 2023. Since then, the passability of X structures has been assessed, and further habitat assessments were completed at X of these. Fish passage has been rehabilitated at X barriers resulting in improved or restored access to X km of habitat. In partnership with the ASF, an old, damaged bridge that was catching debris and creating a blockage in Mill Creek, North Lake Creek watershed, was completely removed, the road was decommissioned and the riparian zone was replanted with native trees and shrubs [(Fish are swimming a bit easier in this P.E.I. creek thanks to bridge structure removal | CBC News)](https://www.cbc.ca/news/canada/prince-edward-island/pei-bridge-removed-improved-fish-passage-1.7280811). Follow-up surveys identified Salmon redds upstream of the removed bridge. Secondly, the Hay River culvert and fish ladder downstream of Johnson’s Pond was also removed and replaced with a fish passable bridge. Additionally, between March 2023-24, the over widened, shallow barrier beach on Bear River was temporarily addressed by recreating a narrowed access channel and deeper thalweg with meandering rocks, with the goal of improving access for the 2023 fall Atlantic Salmon run. Other projects related to top-ranked structures include bathymetric surveys completed at Larkins pond in 2025, designed to assess the amount of sediment accumulation in the reservoir since the dam construction and determine potential next steps to addressing passage at the denil fish ladder.  