
# Acknowledgements and References {-}

## Recommended Citation 

Miller, K. Braceland, F. Mazany-Wright, F. Montgomery, B. Rebellato, and N. W. R. Lapointe. 2026. Northeastern PEI watershed connectivity restoration plan. Canadian Wildlife Federation. Ottawa, Ontario, Canada. 

## Acknowledgements {-}

The Souris and Area Branch of the PEI Wildlife Federation recognizes that the lands and waters that form the basis of this plan are located on Mi’kma’ki, the ancestral and unceded territory of the Mi’kmaq peoples. Members of the planning team (Appendix B) are passionate about the conservation and restoration of freshwater ecosystems and the species they support, and contributed feedback, guidance, and knowledge. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.  

## References {-}

Amiro, P. (1993). Habitat measurement and population estimation of juvenile atlantic salmon (salmo salar). Canadian Special Publication of Fisheries; Aquatic Sciences: Department of Fisheries; Oceans. 

Forbes, D. L., Taylor, R. B., Shaw, J., Carter, R. W. G., & Orford, J. D. (1990). Development and stability of barrier beaches on the atlantic coast of nova scotia. Proceedings, Canadian Coastal Conference, 83–98. 